---
title: "CellChat"
author: "GinoBonazza (ginoandrea.bonazza@usz.ch)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

```{r knitr config, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(warning = FALSE)

knitr::opts_chunk$set(message = FALSE)

knitr::opts_chunk$set(cache = FALSE)

knitr::opts_chunk$set(dpi = 300, fig.align = "center")
```

## Setup

```{r setup, class.source = "fold-hide"}
# Get current file name to make folder
current_file <- "CellChat"

# Load libraries
library(here)
library(readr)
library(readxl)
library(xlsx)
library(Seurat)
library(DropletUtils)
library(Matrix)
library(scDblFinder)
library(scCustomize)
library(dplyr)
library(ggplot2)
library(magrittr)
library(tidyverse)
library(reshape2)
library(S4Vectors)
library(SingleCellExperiment)
library(pheatmap)
library(png)
library(gridExtra)
library(knitr)
library(scales)
library(RColorBrewer)
library(Matrix.utils)
library(tibble)
library(ggplot2)
library(scater)
library(patchwork)
library(statmod)
library(ArchR)
library(clustree)
library(speckle)
library(ggplot2)
library(scater)
library(gprofiler2)
library(clusterProfiler)
library(org.Hs.eg.db)
library(AnnotationHub)
library(ReactomePA)
library(speckle)
library(reactable)
library(CellChat)
library(patchwork)

#Output paths
output_dir_data <- here::here("output", current_file)
if (!dir.exists(output_dir_data)) dir.create(output_dir_data)

if (!dir.exists(here::here("docs", "figure"))) dir.create(here::here("docs", "figure"))

output_dir_figs <- here::here("docs", "figure", paste0(current_file, ".Rmd"))
if (!dir.exists(output_dir_figs)) dir.create(output_dir_figs)
```


```{r}
iPS_integrated <- readRDS(here::here("output","QC_integration_annotation_Ctr", "iPS_integrated.rds"))
```

```{r options}
options(stringsAsFactors = FALSE)
```

```{r data.input}
data.input <- iPS_integrated[["RNA"]]@data # normalized data matrix
# For Seurat version >= “5.0.0”, get the normalized data via `seurat_object[["RNA"]]$data`
labels <- Idents(iPS_integrated)
meta <- data.frame(labels = labels, row.names = names(labels)) # create a dataframe of the cell labels
```

```{r createCellChat}
cellchat <- createCellChat(object = iPS_integrated, group.by = "ident", assay = "RNA")
cellchat <- addMeta(cellchat, meta = meta)
cellchat <- setIdent(cellchat, ident.use = "labels") # set "labels" as default cell identity
levels(cellchat@idents) # show factor levels of the cell labels
groupSize <- as.numeric(table(cellchat@idents)) # number of cells in each cell group
groupSize
```

```{r CellChatDB}
CellChatDB <- CellChatDB.human 
cellchat@DB <- CellChatDB
```

```{r}
# subset the expression data of signaling genes for saving computation cost
cellchat <- subsetData(cellchat) # This step is necessary even if using the whole database
#future::plan("multisession", workers = 4) # do parallel
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
#> The number of highly variable ligand-receptor pairs used for signaling inference is 692
```

```{r}
cellchat <- computeCommunProb(cellchat, type = "triMean")
cellchat <- filterCommunication(cellchat, min.cells = 10)
```

```{r}
df.net <- subsetCommunication(cellchat)
```

```{r}
cellchat <- computeCommunProbPathway(cellchat)
```

```{r}
cellchat <- aggregateNet(cellchat)
```

```{r, fig.width=9, fig.height=3}
groupSize <- as.numeric(table(cellchat@idents))
par(mfrow = c(1,2), mar = c(0, 0, 2, 0), xpd=TRUE)
netVisual_circle(cellchat@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Number of interactions")
netVisual_circle(cellchat@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")
```

```{r, fig.width=9, fig.height=5}
mat <- cellchat@net$weight
par(mfrow = c(2,3), mar = c(0, 4, 0, 4), xpd=TRUE)
for (i in 1:nrow(mat)) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[i])
}
```

```{r, fig.height=6, fig.width=8}
netVisual_chord_gene(cellchat, sources.use = 5, targets.use = c(1:2), lab.cex = 0.5,legend.pos.y = 30, thresh = 0.00001)
```

```{r}
# Run the analysis without parallel processing
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP")

gg1 <- netAnalysis_signalingRole_scatter(cellchat)
gg1
```

```{r, fig.height=13, fig.width=10}
# Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
ht1 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing", width = 10,
  height = 25)
ht2 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "incoming", width = 10,
  height = 25)
ht1 + ht2
```

```{r, eval=FALSE}
netVisual_chord_gene(cellchat, sources.use = c(5), targets.use = c(1:2), slot.name = "netP", legend.pos.x = 10, thresh = 0.00001)
```

```{r, eval = FALSE}
# (1) show all the significant interactions (L-R pairs) from some cell groups (defined by 'sources.use') to other cell groups (defined by 'targets.use')
netVisual_bubble(cellchat, sources.use = 5, targets.use = c(1:2), remove.isolate = FALSE)
#> Comparing communications on a single object
```

```{r}
saveRDS(cellchat, 
        here::here(output_dir_data, "iPS_cellchat.rds"))
```

