---
title: "New figures 14-11-2024"
author: "GinoBonazza (ginoandrea.bonazza@usz.ch)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

```{r knitr config, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  cache = FALSE,
  dpi = 300,
  fig.align = "center"
)
```

## Setup

```{r setup, class.source = "fold-hide"}
# Get current file name to make folder
current_file <- "New_figures"

# Load libraries
library(here)
library(readr)
library(readxl)
library(xlsx)
library(Seurat)
library(DropletUtils)
library(Matrix)
library(scDblFinder)
library(scCustomize)
library(dplyr)
library(ggplot2)
library(magrittr)
library(tidyverse)
library(reshape2)
library(S4Vectors)
library(SingleCellExperiment)
library(pheatmap)
library(png)
library(gridExtra)
library(knitr)
library(scales)
library(RColorBrewer)
library(scater)
library(patchwork)
library(limma)
library(gridExtra)
library(knitr)
library(scales)
library(clusterProfiler)
library(org.Hs.eg.db)
library(AnnotationHub)
library(ReactomePA)
library(EnhancedVolcano)
library(RColorBrewer)
library(Matrix.utils)
library(DESeq2)
library(tibble)
library(speckle)
library(limma)
library(ggplot2)
library(scater)
library(patchwork)
library(statmod)
library(edgeR)
library(dplyr)
library(ggplot2)

#Output paths
output_dir_data <- here::here("output", current_file)
if (!dir.exists(output_dir_data)) dir.create(output_dir_data)

if (!dir.exists(here::here("docs", "figure"))) dir.create(here::here("docs", "figure"))

output_dir_figs <- here::here("docs", "figure", paste0(current_file, ".Rmd"))
if (!dir.exists(output_dir_figs)) dir.create(output_dir_figs)
```

```{r Load dataset}
iPS_integrated <- readRDS(here::here("output", "QC_integration_annotation", "iPS_integrated.rds"))
```

```{r}
iPS_integrated <- subset(iPS_integrated, Cell_line %in% c("JD6", "JDR"))
```

```{r rename CDKN1A}
iPS_integrated$cell_type <- factor(iPS_integrated$cell_type, levels = c("Atrial Cardiomyocytes", 
                                                                        "Ventricular Cardiomyocytes",
                                                                        "Unspecified cells",
                                                                        "Fibroblasts",
                                                                        "Progenitor cells",
                                                                        "Endothelial cells"))
iPS_integrated@meta.data[iPS_integrated@meta.data$integrated_snn_res.0.2 %in% c("2"), "cell_type"] = "Unspecified cells"
table(iPS_integrated$cell_type)
```

```{r UMAP_samples_4, fig.width=5, fig.height=3}
DimPlot(subset(iPS_integrated, Condition=="Ctr"), pt.size = 0.1, shuffle = T) + 
  ggtitle("Ctr") + 
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        axis.title.x = element_text(size = 11),
        axis.title.y = element_text(size = 11))
```

```{r , fig.width=5, fig.height=3}
DimPlot(subset(iPS_integrated, Condition=="DMD"), pt.size = 0.1, shuffle = T) + 
  ggtitle("DMD") + 
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        axis.title.x = element_text(size = 11),
        axis.title.y = element_text(size = 11))
```

```{r FeatPlot_DYSF_UTRN, fig.width=6, fig.height=6}
FeaturePlot(iPS_integrated, c("DMD", "UTRN"), split.by = "Condition", pt.size = 0.3)
```

```{r VlnPlot_DYSF_UTRN, fig.width=13, fig.height=5}
p1 <- VlnPlot(iPS_integrated, c("DMD"), group.by = "cell_type",split.by = "Condition") + NoLegend() + theme(axis.title.x = element_blank())
p2 <- VlnPlot(iPS_integrated, c("UTRN"), group.by = "cell_type",split.by = "Condition") + theme(axis.title.x = element_blank())
p1 | p2
```

```{r Markers}
DefaultAssay(iPS_integrated) <- "SCT"
Idents(iPS_integrated) <- "cell_type"
Markers <- FindAllMarkers(iPS_integrated, only.pos = TRUE, min.pct = 0.5, logfc.threshold = 0.5, recorrect_umi=F)
write.csv(Markers, here::here(output_dir_data, "iPS_Markers_all_cell_type.csv"))
Markers_top10 <- as.data.frame(Markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC))
write.csv(Markers_top10, here::here(output_dir_data, "iPS_Markers_top10_cell_type.csv"))
Markers_top3 <- as.data.frame(Markers %>% group_by(cluster) %>% top_n(n = 3, wt = avg_log2FC))
write.csv(Markers_top3, here::here(output_dir_data, "iPS_Markers_top3_cell_type.csv"))
```

```{r DotPlot_markers_Ctr, fig.width=10, fig.height=5}
Markers_top5 <- as.data.frame(Markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC))
Idents(iPS_integrated) <- factor(iPS_integrated$cell_type, levels = rev(levels(iPS_integrated$cell_type)))
DotPlot(subset(iPS_integrated, Condition == "Ctr"), assay = "SCT", features = Markers_top5$gene, dot.scale = 5) +
  RotatedAxis() +
  theme(axis.title = element_blank(), axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 13), legend.text = element_text(size = 9), legend.title = element_text(size = 11), plot.margin = unit(c(0, 0, 0, 0.1), 
                           "inches")) + ggtitle("Ctr") + 
  theme(plot.title = element_text(hjust = 0.5,      
                                  face = "bold",     
                                  size = 20))
```

```{r, fig.width=10, fig.height=5}
Markers_top5 <- as.data.frame(Markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC))
Idents(iPS_integrated) <- factor(iPS_integrated$cell_type, levels = rev(levels(iPS_integrated$cell_type)))
DotPlot(subset(iPS_integrated, Condition == "DMD"), assay = "SCT", features = Markers_top5$gene, dot.scale = 5) +
  RotatedAxis() +
  theme(axis.title = element_blank(), axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 13), legend.text = element_text(size = 9), legend.title = element_text(size = 11), plot.margin = unit(c(0, 0, 0, 0.1), 
                           "inches")) + ggtitle("DMD") + 
  theme(plot.title = element_text(hjust = 0.5,      
                                  face = "bold",     
                                  size = 20))
```

```{r , fig.height=6, fig.width=9, message=FALSE}
colors <- hue_pal()(6)

props <- getTransformedProps(iPS_integrated$cell_type, iPS_integrated$Sample, transform="logit")

par(mar = c(8, 5, 1, 20), xpd = TRUE)
barplot(props$Proportions, legend = FALSE, ylab = "Proportions", col = colors, 
        cex.names = 1.6, las = 2, font.lab = 2, font.axis = 2, cex.axis = 1, cex.lab = 1.6)
legend("topright", inset = c(-0.95, 0.13), legend = rownames(props$Proportions), fill = colors, bty = "n", cex = 1.6)
```

```{r}
table(iPS_integrated$cell_type)
CM <- subset(iPS_integrated, subset = cell_type %in% c("Atrial Cardiomyocytes", "Ventricular Cardiomyocytes"))
table(CM$cell_type)
Idents(CM) <- CM$Condition
DefaultAssay(CM) <- "RNA"
CM <- NormalizeData(CM)
CM <- ScaleData(CM)
```


```{r, eval=FALSE}
DE_all <- FindMarkers(CM, test.use = "MAST", ident.1 = "DMD", ident.2 = "Ctr", min.pct = 0.05, logfc.threshold = 0.1, assay = "RNA")
DE_all$gene <- rownames(DE_all)
write.csv(DE_all, file = here::here(output_dir_data, "DE_all.csv"), quote=F, row.names = F)

DE_JDR <- FindMarkers(subset(CM, subset = Cell_line == "JDR"), test.use = "MAST", ident.1 = "DMD", ident.2 = "Ctr", min.pct = 0.05, logfc.threshold = 0.1, assay = "RNA")
DE_JDR$gene <- rownames(DE_JDR)
write.csv(DE_JDR, file = here::here(output_dir_data, "DE_JDR.csv"), quote=F, row.names = F)


DE_JD6 <- FindMarkers(subset(CM, subset = Cell_line == "JD6"), test.use = "MAST", ident.1 = "DMD", ident.2 = "Ctr", min.pct = 0.05, logfc.threshold = 0.1, assay = "RNA")
DE_JD6$gene <- rownames(DE_JD6)
write.csv(DE_JD6, file = here::here(output_dir_data, "DE_JD6.csv"), quote=F, row.names = F)
```

```{r}
DE_all <- read.csv(file = here::here(output_dir_data, "DE_all.csv"))
DE_JDR <- read.csv(file = here::here(output_dir_data, "DE_JDR.csv"))
DE_JD6 <- read.csv(file = here::here(output_dir_data, "DE_JD6.csv"))
```

## log2FC treshold at 0.25

```{r}
signif_JDR <- filter(DE_JDR, abs(avg_log2FC) > 0.5 & p_val_adj < 0.05)

signif_JD6 <- filter(DE_JD6, abs(avg_log2FC) > 0.5 & p_val_adj < 0.05)

signif_all <- filter(DE_all, abs(avg_log2FC) > 0.5 & p_val_adj < 0.05)

common_up <- Reduce(intersect, list(filter(signif_JDR, avg_log2FC > 0.25)$gene,
                                    filter(signif_JD6, avg_log2FC > 0.25)$gene,
                                    filter(signif_all, avg_log2FC > 0.25)$gene))

common_down <- Reduce(intersect, list(filter(signif_JDR, avg_log2FC < -0.25)$gene,
                                      filter(signif_JD6, avg_log2FC < -0.25)$gene,
                                      filter(signif_all, avg_log2FC < 0.25)$gene))

common_genes <- union(common_up, common_down)

common_FC <- data.frame(
  gene = common_genes,
  avg_logFC_all = signif_all %>%
    filter(gene %in% common_genes) %>%
    arrange(gene) %>%
    pull(avg_log2FC),
  avg_logFC_JDR = signif_JDR %>%
    filter(gene %in% common_genes) %>%
    arrange(gene) %>%
    pull(avg_log2FC),
  avg_logFC_JD6 = signif_JD6 %>%
    filter(gene %in% common_genes) %>%
    arrange(gene) %>%
    pull(avg_log2FC)
) %>%
  arrange(avg_logFC_all)
```

```{r }
volcano <- list()
volcano[[1]] <- EnhancedVolcano(DE_all,
                  lab = DE_all$gene,
                  x = "avg_log2FC",
                  y = "p_val_adj",
                  labSize = 0,
                  titleLabSize = 16,
                  subtitleLabSize = 14,
                  axisLabSize = 12,
                  captionLabSize = 9,
                  pointSize = 0.5,
                  FCcutoff = 0.25,
                  pCutoff  = 0.05,
                  col = c("black", "black", "black", "red"),
                  colAlpha = 1,
                  drawConnectors = FALSE,
                  boxedLabels = FALSE,
                  subtitle = NULL,
                  title = "All Cardiomyocytes"
  ) + theme(legend.position = "none")
names(volcano)[1] <- "All"

volcano[[2]] <- EnhancedVolcano(DE_JDR,
                  lab = DE_JDR$gene,
                  x = "avg_log2FC",
                  y = "p_val_adj",
                  labSize = 0,
                  titleLabSize = 16,
                  subtitleLabSize = 14,
                  axisLabSize = 12,
                  captionLabSize = 9,
                  pointSize = 0.5,
                  FCcutoff = 0.25,
                  pCutoff  = 0.05,
                  col = c("black", "black", "black", "red"),
                  colAlpha = 1,
                  drawConnectors = FALSE,
                  boxedLabels = FALSE,
                  subtitle = NULL,
                  title = "JDR Cardiomyocytes"
  ) + theme(legend.position = "none")
names(volcano)[2] <- "JDR"

volcano[[3]] <- EnhancedVolcano(DE_JD6,
                  lab = DE_JD6$gene,
                  x = "avg_log2FC",
                  y = "p_val_adj",
                  labSize = 0,
                  titleLabSize = 16,
                  subtitleLabSize = 14,
                  axisLabSize = 12,
                  captionLabSize = 9,
                  pointSize = 0.5,
                  FCcutoff = 0.25,
                  pCutoff  = 0.05,
                  col = c("black", "black", "black", "red"),
                  colAlpha = 1,
                  drawConnectors = FALSE,
                  boxedLabels = FALSE,
                  subtitle = NULL,
                  maxoverlapsConnectors = 15,
                  max.overlaps = 15,
                  title = "JD6 Cardiomyocytes"
  ) + theme(legend.position = "none")
names(volcano)[3] <- "JD6"
```

```{r , fig.height=5, fig.width=12}
combined_plots <- (volcano[[1]] | volcano[[2]] | volcano[[3]])
print(combined_plots)
```

```{r}
down_genes <- c("B2M", "HLA-C", "ITGA1", "DPYSL3", "PDLIM3", "ZBTB7C")
```

```{r , fig.width=4, fig.height=4}
VlnPlot(CM, features = "LINC01405", group.by = "Cell_line", split.by = "Condition", ncol = 1, pt.size = 0.01)
```

```{r , fig.width=12, fig.height=8}
VlnPlot(CM, features = down_genes, group.by = "Cell_line", split.by = "Condition", ncol = 3, pt.size = 0.01)
```

https://www.biorxiv.org/content/10.1101/2021.02.01.429136v2.full.pdf

```{r , fig.width=3, fig.height=3}
FeaturePlot(CM, features = c("LINC01405"), ncol=1)
```

```{r , fig.width=6, fig.height=3}
FeaturePlot(CM, features = c("MYL2", "MYH7"), ncol=2)
```

```{r , fig.height=6, fig.width=9}
FeaturePlot(subset(iPS_integrated, cell_type %in% c("Atrial Cardiomyocytes", "Ventricular Cardiomyocytes")), features = down_genes, ncol = 3)
```
